### ISSUE TITLE
GOOD boilerplate!

### ISSUE THREAD

**Issue by Alvazz** [H0llyW00dzZ/My-RESTAPIs-Boilerplate#941]
Very clean, orderly and neat architecture design, a good starting point for various types of projects.

If more guidance is provided, Perfect!!!

**Comment by H0llyW00dzZ** [comment]
> Very clean, orderly and neat architecture design, a good starting point for various types of projects.
> 
> If more guidance is provided, Perfect!!!

It was designed to ensures that there's no need to rewrite everything when it's already secure and functional. In Go, when building a web application, everything is already secure, functional, and stable, so there's no need to rewrite it again. For the rest, it only depends on the version of Go being used.

**Comment by Alvazz** [comment]
so.. how to use this boilerplate for real project?
For example, I want to develop a restful api with this boilerplate.

**Comment by Alvazz** [comment]
When I cloned and tried to run, I got the following error

<img width="1360" alt="image" src="https://github.com/user-attachments/assets/91839d0e-af64-4a6e-957c-d176d4384b4b">

**Comment by H0llyW00dzZ** [comment]
> When I cloned and tried to run, I got the following error
> 
> <img alt="image" width="1360" src="https://private-user-images.githubusercontent.com/50744096/368728426-91839d0e-af64-4a6e-957c-d176d4384b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NjMzMDIsIm5iZiI6MTcyNjc2MzAwMiwicGF0aCI6Ii81MDc0NDA5Ni8zNjg3Mjg0MjYtOTE4MzlkMGUtYWY2NC00YTZlLTk1N2MtZDE3NmQ0Mzg0YjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE2MjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYWI4OTU0NzFjZDA5ZDI2NWNjNGJkM2VhNmUzODcyYmEyODgzNzQ5NjQ2YzliNDIxODM0Yjk1ZGMzYzg0OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q6NwQvUffl-AuNXg6Hk_9fICw0dSmbv6Vv6F93oHa1I">

@Alvazz You need to set up the environment variables.

The list of environment variables can be found here:

https://github.com/H0llyW00dzZ/My-RESTAPIs-Boilerplate/blob/master/env/env.go

**Comment by H0llyW00dzZ** [comment]
Additionally, check the latest commit:
- #947

**Comment by Alvazz** [comment]
Thanks!
